/**
 * Prints the secrets a Texor Account deployment needs.
 *
 *   node scripts/generate-keys.js
 *
 * Copy the output into .env (or your secret manager). Rotating OIDC_JWKS means
 * keeping the old key in the array until every issued token has expired —
 * the provider publishes every key in the array on the JWKS endpoint, so
 * verification keeps working through the overlap.
 */
import { randomBytes } from 'node:crypto';
import { exportJWK, generateKeyPair } from 'jose';

const { privateKey } = await generateKeyPair('RS256', { extractable: true });
const jwk = await exportJWK(privateKey);

const keys = [{
  ...jwk,
  use: 'sig',
  alg: 'RS256',
  kid: randomBytes(8).toString('hex'),
}];

const line = (key, value) => `${key}=${value}`;

console.log('# Generated by scripts/generate-keys.js — treat every value below as a secret.\n');
console.log(line('OIDC_JWKS', JSON.stringify(keys)));
console.log(line('SECRET_ENCRYPTION_KEY', randomBytes(32).toString('base64')));
console.log(line('COOKIE_KEYS', `${randomBytes(32).toString('base64url')},${randomBytes(32).toString('base64url')}`));
